### ISSUE TITLE
Network.cpp, writeToFile() not working for me

### ISSUE THREAD

**Issue by kjhsdgf** [kjhsdgf/Collin-Neural-Network#19]
@patelami3431 
There's a bounds error in

<p>while ((j++) < numLayers) <br />
{<br />
outfile << "w " << j << endl;<br />
outfile << weights[j];<br />
outfile << "b " << j << endl<br />
outfile << biases[j];<br />
}<p>

which is causing a breakpoint in my compiler. Try copypasting the code below into a .cpp and running it. Does it work for you?

#include <dlib\matrix\matrix_math_functions.h>
#include <dlib\matrix.h>
#include <time.h>
#include <math.h>
#include <vector.h>

using namespace dlib;
using namespace std;

typedef matrix<double> Matrix;

const long double distribution(const int);
void randomizeMatrix(Matrix&);
bool writeToFile();

int main()
{
	writeToFile();
	return 0;
}

bool writeToFile()
{
	/*This method creates a file named "Previous_Network_[Day][Time(hhmin)].txt" and
	writes all  the required parameters of the class network in the file.
	This file can be used later to train the existing network or to classify the file
	provided by the user, using the values from any previous network.
	*/
	string trainingDataFilename = "trainingDataFilename.trn";
	string expectedValuesFilename = "expectedValuesFilename.exp";
	double learningRate = 0.1;
	int batchSize = 10;
	int epochs = 100;
	int numLayers = 5;
	std::vector<int> layerSizes = { 4, 20, 20, 30, 3 };

	std::vector<dlib::matrix<double>> weights;
	std::vector<dlib::matrix<double>> biases;

	weights.resize(numLayers);
	biases.resize(numLayers);
	for (int i = 1; i < numLayers; i++)
	{
	weights[i].set_size(layerSizes[i], layerSizes[i - 1]);
	randomizeMatrix(weights[i]);

	biases[i].set_size(layerSizes[i], 1);
	randomizeMatrix(biases[i]);
	}

	ofstream outfile;
	std::vector<int>::iterator i1;
	int i;
	int j(0);
	int k;
	string a("Previous_Network_");
	time_t _tm = time(NULL);
	struct tm * curtime = localtime(&_tm);
	a += asctime(curtime);
	string fileName;

	fileName.resize(24);
	for (i = 0; i < 20; i++)		//gets the name "Previous_Network_[Day]"
		fileName[j++] = a[i];

	for (i = 28; i < 35; i++)	//appends the [time (hhmin)] to name of the file
		if (a[i] != ':')
			fileName[j++] = a[i];

	fileName += ".txt";				//appends ".txt" to the name of the file
	outfile.open(fileName, ios_base::out); //creates the file with name "Previous_Network_[Day][Time(hhmin)].txt"
	if (outfile.is_open())
	{
		cout << "\nCreating file " << fileName << endl;
		outfile << trainingDataFilename << endl;
		outfile << expectedValuesFilename << endl;
		outfile << learningRate << endl;
		outfile << batchSize << endl;
		outfile << epochs << endl;
		outfile << numLayers << endl;
		i1 = layerSizes.begin();
		for (; i1 != layerSizes.end(); i1++)
			outfile << (*i1) << " ";
		outfile << endl;
		j = 0;
		while ((j++) < numLayers)
		{
			outfile << "w " << j << endl;
			outfile << weights[j];			//there is overloaded operator for '<<' to display the matrices inside dlib
			outfile << "b " << j << endl;
			outfile << biases[j];
		}
		outfile.close();
		return true;
	}
	else
	{
		cout << "Server error 401: Could not open the file requested! Try again later..";
		return false;
	}
}

const long double distribution(const int num_neurons_in)
{
	long double v1, v2, w, z1;
	long double variance;

	if (num_neurons_in < 0)
		variance = 1;
	else
		variance = (1 / sqrt(num_neurons_in));

	do {
		v1 = std::rand() + 1;
		v2 = std::rand() + 1;
		v1 /= RAND_MAX + 2;
		v2 /= RAND_MAX + 2;
		v1 = 2 * v1 - 1;
		v2 = 2 * v2 - 1;
		w = v1 * v1 + v2 * v2;
	} while (w >= 1);
	w = sqrt((-2 * log(w)) / w);
	z1 = v1 * w;

	return (z1 * variance);
}

void randomizeMatrix(Matrix &input_matrix)
{
	if (input_matrix.nc() == 1)
	{
		for (int i = 0; i < input_matrix.nr(); i++)
			input_matrix(i) = distribution(-1);
	}
	else
	{
		for (int i = 0; i < input_matrix.nr(); i++)
			for (int j = 0; j < input_matrix.nc(); j++)
				input_matrix(i, j) = distribution(input_matrix.nc());
	}
}

**Comment by patelami3431** [comment]
oh I see, the code ran on my compiler because I had the valid matrices for index 0 too, but for our network we don't have values for 0, so we won't be able to use the overloaded << operator.

**Comment by patelami3431** [comment]
Did you add the matrices at index 0?

**Comment by patelami3431** [comment]
Seems like you didn't assign the values to the weights and biases matrices at index 1. And, that's why the compiler is throwing the error!

**Comment by patelami3431** [comment]
And also, the typedef has to be for matrix<double>

**Comment by patelami3431** [comment]
Yeah, that was working for me when I added the code on GitHub. Let me check what's going on!

**Comment by patelami3431** [comment]
This works!
I am sorry, made a mistake in adding the condition to stop the loop. It worked earlier because my constructor had the number of matrices equal to the numLayers.
Try Copy pasting this. It works perfectly now!

#include <dlib\matrix\matrix_math_functions.h>
#include <dlib\matrix.h>
#include <time.h>
#include <math.h>
#include <vector>
using namespace dlib;
using namespace std;
typedef matrix<double> Matrix;
const long double distribution(const int);
void randomizeMatrix(Matrix&);
bool writeToFile();
int main()
{
	writeToFile();
	return 0;
}
bool writeToFile()
{
	/*This method creates a file named "Previous_Network_[Day][Time(hhmin)].txt" and
	writes all the required parameters of the class network in the file.
	This file can be used later to train the existing network or to classify the file
	provided by the user, using the values from any previous network.
	*/
	string trainingDataFilename = "trainingDataFilename.trn";
	string expectedValuesFilename = "expectedValuesFilename.exp";
	double learningRate = 0.1;
	int batchSize = 10;
	int epochs = 100;
	int numLayers = 5;
	std::vector<int> layerSizes = { 4, 20, 20, 30, 3 };
	std::vector<dlib::matrix<double>> weights;
	std::vector<dlib::matrix<double>> biases;

	weights.resize(numLayers);
	biases.resize(numLayers);
	for (int i = 1; i < numLayers; i++)
	{
		weights[i].set_size(layerSizes[i], layerSizes[i - 1]);
		randomizeMatrix(weights[i]);

		biases[i].set_size(layerSizes[i], 1);
		randomizeMatrix(biases[i]);
	}

	ofstream outfile;
	std::vector<int>::iterator i1;
	int i;
	int j(0);
	int k;
	string a("Previous_Network_");
	time_t _tm = time(NULL);
	struct tm * curtime = localtime(&_tm);
	a += asctime(curtime);
	string fileName;

	fileName.resize(24);
	for (i = 0; i < 20; i++)		//gets the name "Previous_Network_[Day]"
		fileName[j++] = a[i];

	for (i = 28; i < 35; i++)	//appends the [time (hhmin)] to name of the file
		if (a[i] != ':')
			fileName[j++] = a[i];

	fileName += ".txt";				//appends ".txt" to the name of the file
	outfile.open(fileName, ios_base::out); //creates the file with name "Previous_Network_[Day][Time(hhmin)].txt"
	if (outfile.is_open())
	{
		cout << "\nCreating file " << fileName << endl;
		outfile << trainingDataFilename << endl;
		outfile << expectedValuesFilename << endl;
		outfile << learningRate << endl;
		outfile << batchSize << endl;
		outfile << epochs << endl;
		outfile << numLayers << endl;
		i1 = layerSizes.begin();
		for (; i1 != layerSizes.end(); i1++)
			outfile << (*i1) << " ";
		outfile << endl;
		j = 1;
		while (j < numLayers)
		{
			outfile << "w " << j << endl;
			outfile << weights[j];			//there is overloaded operator for '<<' to display the matrices inside dlib
			outfile << "b " << j << endl;
			outfile << biases[j];
			j++;
		}
		outfile.close();
		return true;
	}
	else
	{
		cout << "Server error 401: Could not open the file requested! Try again later..";
		return false;
	}
}
const long double distribution(const int num_neurons_in)
{
	long double v1, v2, w, z1;
	long double variance;
	if (num_neurons_in < 0)
		variance = 1;
	else
		variance = (1 / sqrt(num_neurons_in));

	do {
		v1 = std::rand() + 1;
		v2 = std::rand() + 1;
		v1 /= RAND_MAX + 2;
		v2 /= RAND_MAX + 2;
		v1 = 2 * v1 - 1;
		v2 = 2 * v2 - 1;
		w = v1 * v1 + v2 * v2;
	} while (w >= 1);
	w = sqrt((-2 * log(w)) / w);
	z1 = v1 * w;

	return (z1 * variance);
}
void randomizeMatrix(Matrix &input_matrix)
{
	if (input_matrix.nc() == 1)
	{
		for (int i = 0; i < input_matrix.nr(); i++)
			input_matrix(i) = distribution(-1);
	}
	else
	{
		for (int i = 0; i < input_matrix.nr(); i++)
			for (int j = 0; j < input_matrix.nc(); j++)
				input_matrix(i, j) = distribution(input_matrix.nc());
	}
}
